export const ADD_USER = "ADD_USER";
export const DELETE_TICKET = "DELETE_TICKET";
export const ADD_USER_TICKETS = "ADD_USER_TICKETS";
export const ADD_TICKETS = "ADD_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const REMOVE_USER = "REMOVE_USER";
export const ADD_USER_BUSINESSES = "ADD_USER_BUSINESSES";
export const CLEAR_TICKETS = "CLEAR_TICKETS";